# UW-Madison HTCondor submit file
# process_NCEI_01.sub
universe = vanilla
log = process_NCEI_01.log
error = process_NCEI_01.err
executable = process_NCEI_01.sh
arguments =
output = process_NCEI_01.out
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = python.tar.gz,process_NCEI_01.py
request_cpus = 1
request_memory = 8GB
request_disk = 8GB
requirements = (OpSys == "LINUX") && (OpSysMajorVer == 6) && (Target.HasGluster == true)
queue 1
